# Generated by Django 5.0.1 on 2024-02-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
    ]
